all:
	g++ -std=c++11 serverM.cpp -o serverM
	g++ -std=c++11 client.cpp -o client
	g++ -std=c++11 serverC.cpp -o serverC
	g++ -std=c++11 serverCS.cpp -o serverCS
	g++ -std=c++11 serverEE.cpp -o serverEE

.PHONY: serverM
serverM:
	./serverM

.PHONY: client
client:
	./client

.PHONY: serverC
serverC:
	./serverC

.PHONY: serverCS
serverCS:
	./serverCS

.PHONY: serverEE
serverEE:
	./serverEE